### ISSUE TITLE
Create release with binary files

### ISSUE THREAD

**Issue by txthinking** [zhanhb/cidr-merger#2]
Could you please create a release and upload binary files, such as: `cidr-merger_linux_amd64`.

Then we can get it with [Nami](https://github.com/txthinking/nami/wiki)

```
$ nami install github.com/zhanhb/cidr-merger
```

**Comment by zhanhb** [comment]
https://github.com/zhanhb/cidr-merger/releases/tag/v1.1.1

**Comment by txthinking** [comment]
Could you rename it like `cidr-merger_linux_amd64` please?

**Comment by zhanhb** [comment]
I don't think so.

**Comment by txthinking** [comment]
Thanks
